package com.app.dto;

import java.util.Date;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.Data;

@Data
public class RequestPostDto {
	
	@NotNull
	@NotBlank
	@Length(max = 255)
	private String title;
	
	@NotNull
	@NotBlank
	@Length(max = 255, min = 3)
	private String author;
	
	@Length(min = 50 , max = 1000)
	@NotNull
	@NotBlank
	private String body;
	
	@NotNull
	private String category;
	
	// this date must be in the future
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd")
	private Date event_date;

	/* 
	 * The fields : preview - id - published_at are generated by the server
	 */
	
}
